services:
  app:
    build: .
    container_name: multi_agents_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/multi_agents
      OPENAI_API_KEY: OPENAI_API_KEY_REMOVEDmE8R-mVQS5h1emvzNbOnKt38gQ57yaVb7nL598SfeKljQwpysL7eweckNH8da4sdtoc789mv6jT3BlbkFJJVVXGTPnrz5DzwID0DZxdongR1dXiy5KdKlPCXQPomup7HSmz8RFB4Zln52PM6rvknYjHaYhoA
      PYTHONPATH: /app
    restart: always

  db:
    image: postgres:15
    container_name: multi_agents_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multi_agents
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: